DROP TABLE event IF EXISTS;

-- -----------------------------------------------------------------------------

create table event (
	id bigint generated by default as identity (start with 1),
	name varchar(100) not null,
	eventDate date not null,
	description varchar(100),
	primary key (id)
);
